Models/ChatModel.cs
using System.Collections.Generic;
using System;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Models
{
    public class ChatModel 
    {
        public string user{ get; set;}
        public string message{ get; set;}
        public List<MessagesModel> messages{ get; set;}
    }
}

Models/ErrorViewModel.cs
using System;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ImageMessage.cs
using System;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Models
{
    public class ImageMessage
    {
        public string user{ get; set;}
        public string data { get; set; }
        public string name { get; set; }
        public string header { get; set; }
    }
}

Models/MessagesModel.cs
using System;
using Microsoft.AspNetCore.Http;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Models
{
    public class MessagesModel
    {
        public string Msg{ get; set;}
        public IFormFile FileAttach{ get; set;}
    }
}

Models/UserModel.cs
using System;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Models
{
    public class UserModel
    {
        public string username{ get; set;}
        
    }
}

Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CHAT_DOTNET_CRISATNO_LASSO_VACA.Models;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Controllers
{
    public class ChatController : Controller
    {
        private readonly ILogger<ChatController> _logger;

        public ChatController(ILogger<ChatController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(MessagesModel message)
        {
            Console.Write("nuevo mensaje");
            Console.Write(message.Msg);
            return View(message);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CHAT_DOTNET_CRISATNO_LASSO_VACA.Models;
using CHAT_DOTNET_CRISATNO_LASSO_VACA.Hubs;

namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Controllers
{
    public class FilesController : Controller
    {
        private readonly ILogger<FilesController> _logger;

        public FilesController(ILogger<FilesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

      

        public IActionResult Inbox()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CHAT_DOTNET_CRISATNO_LASSO_VACA.Models;


namespace CHAT_DOTNET_CRISATNO_LASSO_VACA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(UserModel user)
        {
            ChatModel chat = new ChatModel();
            chat.user = user.username;
            return View("../Chat/Index", chat);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Chat/Index.cshtml
@model ChatModel

@{
    ViewData["Title"] = "Chat Page";
}

<section class="text-center">
    <h3> Chat con ASP.NET Core SignalR .NET </h3>
</section>

<section class="card mb-3 p-4">
    <h5 class="card-title text-center">Bienvenido </h5>
    <form method="POST" class="card-body">
        <div class="mb-3">
            <label for="msg" class="form-label">Usuario</label>
            <input class="form-control" name="user" id="userInput"></input>
            <label for="msg" class="form-label">Mensaje</label>
            <input class="form-control" name="message" id="messageInput"></input>
        </div>
        <button type="submit" class="btn btn-primary" id="SendMessageBtn">Enviar</button>
    </form>  
</section>

<section class="card">
    <h5 class="card-title text-center">Buzón de mensajes </h5>

    <ul id="messagesList"></ul>

</section>

<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.7/signalr.min.js"></script>
<script src="~/js/chat_msg.js"></script>

Views/Files/Index.cshtml
<link href="@Url.Content("~/css/files.css")" rel="stylesheet" type="text/css" />


<section class="card mb-3 p-4">
    <form class="card-body">
        <label for="msg" class="form-label">Usuario</label>
        <input class="form-control" name="user" id="userInput"></input>
        <label for="msg" class="form-label">Adjuntar Archivo</label>
        <input type="file" class="form-control btn btn-outline-secondary p-1 " id="filesSending" />
        <button type="submit" class="btn btn-secondary mt-3" id="SendMessageBtn">Enviar Archivo</button>
    </form>
</section>


<section class="card">
    <ul id="messagesList"></ul>
</section>


<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.7/signalr.min.js"></script>
<script src="~/js/chat_files.js"></script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<section class="text-center">
    <h3> Chat con ASP.NET Core SignalR .NET </h3>
</section>

<section>
    <a asp-controller="Chat" asp-action="Index" class="btn btn-primary"> Ingresar al chat </a>
    <hr/>
    <a asp-controller="Files" asp-action="Index" class="btn btn-primary"> Ingresar al chat de archivos </a>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CHAT DOTNET CRISATNO LASSO VACA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Mensajeria de Mensajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Index">Mensajeria de Archivos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Acerca de</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CHAT DOTNET CRISATNO LASSO VACA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Acerca de</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>